[package]
name = "example"
version = "0.1.0"
authors = ["Shadaj Laddad <shadaj@users.noreply.github.com>"]
edition = "2018"

[dependencies]
diplomat = { path = "../macro" }
icu = "0.2"
fixed_decimal = "0.2.0"
