[package]
name = "example"
version = "0.2.0"
authors = ["Shadaj Laddad <shadaj@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[dependencies]
diplomat = { path = "../macro" }
diplomat-runtime = { path = "../runtime" }
icu = { git = "https://github.com/unicode-org/icu4x", branch = "main" }
writeable = { git = "https://github.com/unicode-org/icu4x", branch = "main" }
fixed_decimal = { git = "https://github.com/unicode-org/icu4x", branch = "main" }
icu_provider = { git = "https://github.com/unicode-org/icu4x", branch = "main", features = ["provider_serde"] }
icu_testdata = { git = "https://github.com/unicode-org/icu4x", branch = "main" }
