name: example

publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.0.0
  hooks: ^1.0.0
  meta: ^1.12.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
