# The lib-name is overridden within the code.
lib-name = "This Will Be Ignored For Testing Purposes (Check src/lib.rs)"
unsafe_references_in_callbacks = true

[kotlin]
domain = "dev.diplomattest"
dylib-name = "diplomat_feature_tests"

[demo-gen]
relative-js-path = "../../js/api/"